#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      install
#   created:   18.02.2018.-10:15:37
#   version:   1.0
# -----------------------------------------------------------------------------
# Requirements:
#   curl, git
# Description:
#   Installs vim-anywhere. Intended for use via curl:
#   $ curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/install | bash
# -----------------------------------------------------------------------------
# Script:

err() { echo -e "$@" 1>&2; }

check_installed() { hash "$1" &> /dev/null; }

require_installed() {
  if ! check_installed "$1"; then
    err "vim-anywhere requires $1 to function"
    if [[ "$2" != "" ]]; then echo "$2"; fi
    exit 1
  fi
}

main() {
  AW_PATH=$HOME/.vim-anywhere
  AW_URL='https://github.com/miroslavvidovic/vim-anywhere'

  # pre-installation checks
  # Check if vim-anywhere is already installed. If so, remove the previous
  # installation.
  if [ -a "$AW_PATH" ]; then
    echo 'Cleaning up previous installation...'
    rm -rf "$AW_PATH"
    # TODO: It would be nice to have an option for user input here
    # Reinstall vim-anywhere (y/n)? ... or something like that
  fi

  require_installed git

  # if we are in a git repo, unset env vars
  if git rev-parse --git-dir &> /dev/null; then
    unset "$(git rev-parse --local-env-vars)" &> /dev/null
  fi

  require_installed gvim
  require_installed xclip

  # installation
  echo "Installing vim-anywhere..."

  git clone "$AW_URL" "$AW_PATH"

  echo "vim-anywhere has been successfully installed!"
}

main
