#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      uninstall
#   created:   18.02.2018.-10:45:38
#   version:   1.0
# -----------------------------------------------------------------------------
# Description:
#   Uninstalls vim-anywhere
# -----------------------------------------------------------------------------
# Script:

main(){
  AW_PATH=$HOME/.vim-anywhere
  DOC_PATH=/tmp/vim-anywhere

  # uninstall
  rm -rvf "$AW_PATH" "$DOC_PATH"

  echo "vim-anywhere has been successfully uninstalled!"
}

main
