#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      update
#   created:   18.02.2018.-10:47:14
#   version:   1.0
# -----------------------------------------------------------------------------
# Requirements:
#  git
# Description:
#  Updates vim-anywhere
# -----------------------------------------------------------------------------
# Script:

err() { echo -e "$@" 1>&2; }

main(){
  AW_PATH=$HOME/.vim-anywhere

  if [ ! -d "$AW_PATH" ]; then
    err "vim-anywhere doesn't seem to be installed."
    exit 1
  fi

  # if we are in a git repo, unset env vars
  if git rev-parse --git-dir &> /dev/null; then
    unset "$(git rev-parse --local-env-vars)" &> /dev/null
  fi

  pushd "$AW_PATH"
    git pull origin master
    [ $? -ne 0 ] && exit 1
  popd

  echo "vim-anywhere has been successfully updated!"
}

main
